//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GivensMethod
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MatrixDb : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MatrixDb object using the connection string found in the 'MatrixDb' section of the application configuration file.
        /// </summary>
        public MatrixDb() : base("name=MatrixDb", "MatrixDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MatrixDb object.
        /// </summary>
        public MatrixDb(string connectionString) : base(connectionString, "MatrixDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MatrixDb object.
        /// </summary>
        public MatrixDb(EntityConnection connection) : base(connection, "MatrixDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MatrixModel> MatrixModels
        {
            get
            {
                if ((_MatrixModels == null))
                {
                    _MatrixModels = base.CreateObjectSet<MatrixModel>("MatrixModels");
                }
                return _MatrixModels;
            }
        }
        private ObjectSet<MatrixModel> _MatrixModels;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MatrixModels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMatrixModels(MatrixModel matrixModel)
        {
            base.AddObject("MatrixModels", matrixModel);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MatrixDbModel", Name="MatrixModel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MatrixModel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MatrixModel object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="matrix">Initial value of the matrix property.</param>
        public static MatrixModel CreateMatrixModel(global::System.String id, global::System.String matrix)
        {
            MatrixModel matrixModel = new MatrixModel();
            matrixModel.id = id;
            matrixModel.matrix = matrix;
            return matrixModel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String matrix
        {
            get
            {
                return _matrix;
            }
            set
            {
                OnmatrixChanging(value);
                ReportPropertyChanging("matrix");
                _matrix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("matrix");
                OnmatrixChanged();
            }
        }
        private global::System.String _matrix;
        partial void OnmatrixChanging(global::System.String value);
        partial void OnmatrixChanged();

        #endregion
    
    }

    #endregion
    
}
